Repository gitcoinco/grant-hub, pull requests merged in 2022-10, with the labels that each got.

#387 Issue 366: redirect after round apply
  client/src/__tests__/reducers/roundApplication.test.ts
  client/src/__tests__/utils/RoundApplicationBuilder.test.ts
  client/src/actions/roundApplication.ts
  client/src/components/base/__tests__/formValidation.test.ts
  client/src/components/rounds/Apply.tsx
  client/src/reducers/roundApplication.ts
  client/tailwind.config.js
Labels: enhancement

#418 Update production with latest staging updates
  client/.eslint.js
  client/src/__tests__/components/base/Alert.test.tsx
  client/src/__tests__/components/grants/List.test.tsx
  client/src/__tests__/reducers/grantsMetadata.test.ts
  client/src/__tests__/reducers/roundApplication.test.ts
  client/src/__tests__/reducers/ui.test.ts
  client/src/__tests__/utils/RoundApplicationBuilder.test.ts
  client/src/actions/grantsMetadata.ts
  client/src/actions/newGrant.ts
  client/src/actions/projectForm.ts
  client/src/actions/roundApplication.ts
  client/src/actions/rounds.ts
  client/src/actions/ui.ts
  client/src/components/Layout.tsx
  client/src/components/base/Alert.tsx
  client/src/components/base/ImageInput.tsx
  client/src/components/base/Preview.tsx
  client/src/components/base/ProjectForm.tsx
  client/src/components/base/RoundApplyAlert.tsx
  client/src/components/base/__tests__/formValidation.test.ts
  client/src/components/grants/Edit.tsx
  client/src/components/grants/List.tsx
  client/src/components/grants/New.tsx
  client/src/components/grants/Toggle.tsx
  client/src/components/grants/ToggleDetails.tsx
  client/src/components/icons/Check.tsx
  client/src/components/rounds/Apply.tsx
  client/src/components/rounds/Show.tsx
  client/src/contracts/abis/ProgramImplementation.json
  client/src/contracts/abis/Round.json
  client/src/contracts/abis/RoundImplementation.json
  client/src/index.tsx
  client/src/reducers/grantsMetadata.ts
  client/src/reducers/index.ts
  client/src/reducers/roundApplication.ts
  client/src/reducers/rounds.ts
  client/src/reducers/ui.ts
  client/src/styles/index.css
  client/src/types/alert.ts
  client/src/types/index.ts
  client/src/utils/test_utils.tsx
  client/src/utils/utils.ts
  client/tailwind.config.js
Labels: hold

#419 417 - Update alert for round apply
  client/public/assets/check.svg
  client/src/__tests__/components/base/Alert.test.tsx
  client/src/actions/ui.ts
  client/src/components/application/Form.tsx
  client/src/components/base/Alert.tsx
  client/src/components/base/Preview.tsx
  client/src/components/grants/inputs.tsx
  client/src/components/icons/Check.tsx
  client/src/components/rounds/Apply.tsx
  client/src/styles/index.css
  client/src/types/alert.ts
  client/src/utils/test_utils.tsx
  client/tailwind.config.js
Labels: enhancement, chore

#467 311 Fix typo for round modal
  client/src/components/grants/List.tsx
Labels: bug

#468 add dev ext tools
  client/package.json
  client/src/store.ts
  client/yarn.lock
Labels: tooling

#465 445 - error modal
  client/src/actions/roundApplication.ts
  client/src/components/application/Form.tsx
  client/src/components/base/ErrorModal.tsx
  client/src/components/rounds/Apply.tsx
  client/src/components/rounds/StatusModal.tsx
  client/src/reducers/roundApplication.ts
Labels: enhancement

#447 422 add application status card to project details
  client/src/__tests__/reducers/projects.test.ts
  client/src/actions/projects.ts
  client/src/components/grants/ApplicationCard.tsx
  client/src/components/grants/Details.tsx
  client/src/components/grants/__tests__/ApplicationCard.test.ts
  client/src/components/icons/Calendar.tsx
  client/src/reducers/projects.ts
  client/src/reducers/rounds.ts
  client/src/utils/graphql.ts
  client/tailwind.config.js
Labels: enhancement
