Repository gitcoinco/grant-hub, pull requests merged in 2022-09, with the labels that each got.

#295 parse round contract address to have it case sensitive for LIT protocol
  client/src/services/lit.ts
  client/src/utils/utils.ts
Labels: bug

#289 chore:adding a network check
  client/src/actions/web3.ts
  client/src/components/Layout.tsx
  client/src/reducers/web3.ts
Labels: chore

#288 chore:Add address verification
  client/src/components/application/Form.tsx
  client/src/components/grants/inputs.tsx
  client/src/components/rounds/Apply.tsx
  client/src/types/index.ts
  client/src/utils/wallet.ts
Labels: chore

#328 Make frontend updates to Project Details page
  client/src/actions/projects.ts
  client/src/components/base/Preview.tsx
  client/src/components/grants/Details.tsx
  client/src/components/grants/Show.tsx
  client/src/types/index.ts
Labels: chore

#325 Add project description toggle
  client/src/actions/rounds.ts
  client/src/components/application/Form.tsx
  client/src/components/grants/Toggle.tsx
  client/src/components/grants/ToggleDetails.tsx
  client/src/components/grants/inputs.tsx
Labels: chore

#345 Issue 319: update round landing page to add project if none
  client/src/__tests__/components/rounds/Show.test.tsx
  client/src/actions/rounds.ts
  client/src/components/rounds/Show.tsx
  client/src/types/index.ts
  client/src/utils/test_utils.tsx
Labels: chore

#344 Issue 332: Round application error handling
  client/src/components/application/Form.tsx
  client/src/components/base/__tests__/formValidation.test.ts
  client/src/components/base/formValidation.ts
  client/src/components/grants/Radio.tsx
  client/src/components/grants/inputs.tsx
  client/src/types/index.ts
Labels: enhancement

#331 Fix project form infinite loop
  client/package.json
  client/src/actions/newGrant.ts
  client/src/actions/projectForm.ts
  client/src/components/base/ImageInput.tsx
  client/src/components/base/ProjectForm.tsx
  client/src/reducers/projectForm.ts
Labels: bug

#352 fix of projects not loading - round apply page
  client/jest.config.js
  client/src/__tests__/components/rounds/Show.test.tsx
  client/src/components/application/Form.tsx
  client/src/components/rounds/Show.tsx
Labels: bug

#377 convert metadata to project before sending round application
  client/src/__tests__/components/grants/List.test.tsx
  client/src/__tests__/utils/utils.test.ts
  client/src/actions/roundApplication.ts
  client/src/reducers/grantsMetadata.test.ts
  client/src/types/index.ts
  client/src/utils/test_utils.tsx
  client/src/utils/utils.ts
Labels: bug

#389 fix submit btn on round apply
  client/src/components/application/Form.tsx
Labels: bug

#395 404 UI fixes
  client/src/components/base/PageNotFound.tsx
Labels: chore

#394 Format date and change order of fields in project details
  client/src/components/grants/Details.tsx
  client/src/components/grants/Show.tsx
Labels: chore

#400 add validation colors to config and ui
  client/src/components/application/Form.tsx
  client/tailwind.config.js
Labels: chore

#399 Updates Preview Flow
  client/src/components/application/Form.tsx
Labels: bug

#401 fix validation to add address
  client/src/components/base/__tests__/formValidation.test.ts
  client/src/components/base/formValidation.ts
Labels: chore

#391 Issue 332: update error messaging
  client/src/components/application/Form.tsx
Labels: chore

#380 Issue 193: update error message for github verify failure
  client/src/components/providers/Github.tsx
Labels: enhancement

#397 update prod with development
  client/src/__tests__/components/grants/List.test.tsx
  client/src/__tests__/utils/utils.test.ts
  client/src/actions/roundApplication.ts
  client/src/components/application/Form.tsx
  client/src/components/base/ImageInput.tsx
  client/src/components/base/PageNotFound.tsx
  client/src/components/base/__tests__/formValidation.test.ts
  client/src/components/base/formValidation.ts
  client/src/components/grants/Details.tsx
  client/src/components/grants/Radio.tsx
  client/src/components/grants/Show.tsx
  client/src/components/grants/Toggle.tsx
  client/src/components/grants/ToggleDetails.tsx
  client/src/components/grants/inputs.tsx
  client/src/components/providers/Github.tsx
  client/src/components/rounds/Apply.tsx
  client/src/reducers/grantsMetadata.test.ts
  client/src/types/index.ts
  client/src/utils/test_utils.tsx
  client/src/utils/utils.ts
  client/tailwind.config.js
Labels: hold

#405 update label for payout address
  client/src/components/application/Form.tsx
Labels: chore

#396 Improvements to project details UI
  client/src/components/grants/Toggle.tsx
  client/src/components/grants/ToggleDetails.tsx
  client/src/styles/index.css
Labels: chore
