Repository gitcoinco/grant-hub, pull requests merged in 2022-11, with the labels that each got.

#501 304 Nav Customer Support
  client/src/__tests__/components/base/CustomerSupport.test.tsx
  client/src/components/Header.tsx
  client/src/components/base/CustomerSupport.tsx
  client/src/components/grants/Edit.tsx
  client/src/components/grants/List.tsx
  client/src/components/grants/New.tsx
  client/src/components/rounds/Apply.tsx
  client/tailwind.config.js
Labels: feature

#500 358-set up footer and icons
  client/src/components/Footer.tsx
  client/src/components/Layout.tsx
  client/src/components/grants/Landing.tsx
  client/src/components/icons/Code.tsx
  client/src/components/icons/Discord.tsx
  client/src/components/icons/Github.tsx
  client/src/components/icons/Support.tsx
Labels: feature

#502 456 - updates chains available in prod
  client/src/utils/wagmi.ts
Labels: chore

#503 245 - add og meta tags for image, etc.
  client/public/assets/gh-background.svg
  client/public/index.html
Labels: chore

#516 511-project-app-loading
  client/src/actions/roundApplication.ts
Labels: bug

#498 404 - Project form changes
  client/src/components/base/ProjectForm.tsx
  client/src/components/base/VerificationForm.tsx
  client/src/components/providers/Github.tsx
  client/src/components/providers/Twitter.tsx
Labels: enhancement

#527 upddate for bug fix
  client/src/components/base/Preview.tsx
  client/src/components/grants/Details.tsx
  client/src/components/grants/Show.tsx
Labels: bug

#549 548 updates to state prop and remove timeout after project edit
  client/src/__tests__/reducers/projects.test.ts
  client/src/components/base/Preview.tsx
  client/src/components/grants/Details.tsx
  client/src/components/grants/List.tsx
  client/src/reducers/projects.ts
Labels: chore

#554 error fetching project apps
  client/src/actions/projects.ts
  client/src/utils/graphql.ts
Labels: bug, chore

#584 add optimism to production chain selection
  client/src/utils/wagmi.ts
Labels: chore
